### ISSUE TITLE
ECONNREFUSED when attempting to import

### ISSUE THREAD

**Issue by migurski** [pelias/openaddresses#104]
I am attempting to import one CSV file of OpenAddresses data, and finding this error. I have previously created an index.

```
% node import.js

2016-05-05T03:42:56.151Z - info: [openaddresses] Importing 1 files.
2016-05-05T03:42:57.091Z - info: [openaddresses] Creating read stream for: /mnt/pelias/openaddresses/alameda.csv
Elasticsearch ERROR: 2016-05-05T03:42:59Z
  Error: Request error, retrying
  POST http://localhost:9200/_bulk => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (/home/migurski/pelias-openaddresses/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/home/migurski/pelias-openaddresses/node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (/home/migurski/pelias-openaddresses/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (/home/migurski/pelias-openaddresses/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at emitOne (events.js:77:13)
      at ClientRequest.emit (events.js:169:7)
      at Socket.socketErrorListener (_http_client.js:258:9)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at emitErrorNT (net.js:1256:8)

Elasticsearch ERROR: 2016-05-05T03:42:59Z
  Error: Request error, retrying
  POST http://localhost:9200/_bulk => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (/home/migurski/pelias-openaddresses/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/home/migurski/pelias-openaddresses/node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (/home/migurski/pelias-openaddresses/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (/home/migurski/pelias-openaddresses/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at emitOne (events.js:77:13)
      at ClientRequest.emit (events.js:169:7)
      at Socket.socketErrorListener (_http_client.js:258:9)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at emitErrorNT (net.js:1256:8)

(repeats many times)
```

The ES server is responding as I would expect:

```
% curl -i http://localhost:9200/

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 332

{
  "status" : 200,
  "name" : "Sack",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.5",
    "build_hash" : "00f95f4ffca6de89d68b7ccaf80d148f1f70e4d4",
    "build_timestamp" : "2016-02-02T09:55:30Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

I am using OpenJDK 8 on Ubuntu 16.04, with Node 4.2.6.

**Comment by migurski** [comment]
This seemed to work when I tried later on—unsure what was happening, but I wasn’t able to replicate this problem today.
