### ISSUE TITLE
Docker-based install fails on "download oa" step

### ISSUE THREAD

**Issue by OKNoah** [pelias/openaddresses#387]
Using pelias/docker command-line tool, I get this error. It seems to happen to matter what `files` I use:

```bash
~/P/p/p/france > pelias download oa

> pelias-openaddresses@0.0.0-development download /code/pelias/openaddresses
> node utils/download_data.js

info: [download] Attempting to download selected data files: fr/ain.csv
info: [download] Downloading fr/ain.csv
debug: [download] downloading https://results.openaddresses.io/latest/run/fr/ain.zip
debug: [download] unzipping /tmp/tmp-2717RJ2S0YUpaT.zip to /data/openaddresses
error: [download] Failed to download data message=Command failed: unzip -o -qq -d /data/openaddresses /tmp/tmp-2717RJ2S0YUpaT.zip
[/tmp/tmp-2717RJ2S0YUpaT.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tmp-2717RJ2S0YUpaT.zip or
        /tmp/tmp-2717RJ2S0YUpaT.zip.zip, and cannot find /tmp/tmp-2717RJ2S0YUpaT.zip.ZIP, period.
, stack=Error: Command failed: unzip -o -qq -d /data/openaddresses /tmp/tmp-2717RJ2S0YUpaT.zip
[/tmp/tmp-2717RJ2S0YUpaT.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tmp-2717RJ2S0YUpaT.zip or
        /tmp/tmp-2717RJ2S0YUpaT.zip.zip, and cannot find /tmp/tmp-2717RJ2S0YUpaT.zip.ZIP, period.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5), killed=false, code=9, signal=null, cmd=unzip -o -qq -d /data/openaddresses /tmp/tmp-2717RJ2S0YUpaT.zip
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pelias-openaddresses@0.0.0-development download: `node utils/download_data.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pelias-openaddresses@0.0.0-development download script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-10T14_34_35_155Z-debug.log
```

Excerpt from `pelias.json`

```json
"openaddresses": {
  "datapath": "/data/openaddresses",
  "files": ["fr/ain.csv"]
}
```

**Comment by missinglink** [comment]
Hi @OKNoah,

Which operating system are you using?

Could you please post the output of `unzip --version` on your CLI.

**Comment by OKNoah** [comment]
@missinglink macOS 10.13.6 (17G65)

```bash
unzip --version
caution:  both -n and -o specified; ignoring -o
UnZip 6.00 of 20 April 2009, by Info-ZIP
```

Things did eventually seem to work, but I'm not positive about why exactly at the moment.
