### ISSUE TITLE
missing download causes error, despite missingFilesAreFatal=false

### ISSUE THREAD

**Issue by arne-cl** [pelias/openaddresses#425]
The importer (`v2.28.2`) crashes if there is a filepath in `imports.openaddresses.files` that returns a 404.
In this case it's `ch/schwyz.csv`, which attempts to download https://results.openaddresses.io/latest/run/ch/schwyz.zip (`404 No latest run found`).

```
$ PELIAS_CONFIG=pelias-minimal-test.json node utils/download_data.js 
{"level":"info","message":"Attempting to download selected data files: ch/schwyz.csv,be/wal/namur.csv","label":"openaddresses-download","timestamp":"2019-06-12T15:37:56.130Z"}
{"level":"info","message":"Downloading ch/schwyz.csv","label":"openaddresses-download","timestamp":"2019-06-12T15:37:56.134Z"}
{"level":"info","message":"Downloading be/wal/namur.csv","label":"openaddresses-download","timestamp":"2019-06-12T15:37:56.138Z"}
{"message":"Failed to download data","stack":"Error: Command failed: unzip -o -qq -d /data/openaddresses /data/openaddresses/ch-schwyz19684xKaIon45vP5C.zip\n[/data/openaddresses/ch-schwyz19684xKaIon45vP5C.zip]\n  End-of-central-directory signature not found.  Either this file is not\n  a zipfile, or it constitutes one disk of a multi-part archive.  In the\n  latter case the central directory and zipfile comment will be found on\n  the last disk(s) of this archive.\nunzip:  cannot find zipfile directory in one of /data/openaddresses/ch-schwyz19684xKaIon45vP5C.zip or\n        /data/openaddresses/ch-schwyz19684xKaIon45vP5C.zip.zip, and cannot find /data/openaddresses/ch-schwyz19684xKaIon45vP5C.zip.ZIP, period.\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:189:13)\n    at maybeClose (internal/child_process.js:970:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)","killed":false,"code":9,"signal":null,"cmd":"unzip -o -qq -d /data/openaddresses /data/openaddresses/ch-schwyz19684xKaIon45vP5C.zip","level":"error","label":"download","timestamp":"2019-06-12T15:37:56.636Z"}

$ cat pelias-minimal-test.json
    {
      "logger": {
        "level": "info",
        "json": true,
        "timestamp": true
      },
      "imports": {
        "openaddresses": {
          "missingFilesAreFatal": false,
          "datapath": "/data/openaddresses",
          "files": ["ch/schwyz.csv", "be/wal/namur.csv"]
        }
      }
    }
```

**Comment by orangejulius** [comment]
Hey @arne-cl,
Thanks for reporting this, it's definitely been a bug for quite a while. It should be taken care of by https://github.com/pelias/openaddresses/pull/427. Let me know if not!
