### ISSUE TITLE
Error: EACCES: permission denied, open '/root/openaddresses/.git/hooks/pre-commit'

### ISSUE THREAD

**Issue by biskandar** [pelias/openaddresses#426]
# npm -v
6.9.0

# node -v
v10.16.0

# npm install
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

> git-validate@2.2.4 install /root/openaddresses/node_modules/git-validate
> node bin/install

fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open '/root/openaddresses/.git/hooks/pre-commit'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.exports.installHooks (/root/openaddresses/node_modules/git-validate/lib/utils.js:259:12)
    at Object.<anonymous> (/root/openaddresses/node_modules/git-validate/bin/install.js:3:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! git-validate@2.2.4 install: `node bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-validate@2.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-18T03_47_23_965Z-debug.log

**Comment by missinglink** [comment]
This looks like a permissions issue.

The file `/root/openaddresses/.git/hooks/pre-commit` is probably owned by `root` is that correct?
Is it possible that the command you executed does not have permission to that file?
