### ISSUE TITLE
Maximum call stack size exceeded when running `pelias openaddresses import` using node LTS (v4)

### ISSUE THREAD

**Issue by devTristan** [pelias/openaddresses#44]
```
# pelias openaddresses import
pelias: Cloning repo.
pelias: npm installing.
WARN engine elasticsearch@2.4.3: wanted: {"node":">=0.8 <0.11"} (current: {"node":"4.2.6","npm":"2.14.12"})
npm WARN deprecated lodash-node@2.4.1: This package is no longer maintained. See its readme for upgrade details.
2016-02-05T21:22:03.133Z - info: [openaddresses] Importing 665 files.
2016-02-05T21:22:03.319Z - info: [openaddresses] Total time taken: .243s
events.js:397
EventEmitter.listenerCount = function(emitter, type) {
                                     ^

RangeError: Maximum call stack size exceeded
    at Function.EventEmitter.listenerCount (events.js:397:38)
    at Log.listenerCount (/root/.pelias/openaddresses/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/root/.pelias/openaddresses/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/root/.pelias/openaddresses/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/root/.pelias/openaddresses/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/root/.pelias/openaddresses/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/log.js:68:25)
child_process.js:507
    throw err;
    ^

Error: Command failed: node import.js 
    at checkExecSyncError (child_process.js:464:13)
    at Object.execSync (child_process.js:504:13)
    at runRepoSubcommand (/usr/local/lib/node_modules/pelias-cli/pelias.js:193:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/pelias-cli/pelias.js:196:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
```

Works fine with 0.12.x

**Comment by orangejulius** [comment]
Hey @devTristan,
Thanks for reporting this, although we've known about it for a while. I've dug into things a bit and think I've found most of the NodeJS issues. Hopefully we will have at least preliminary support sometime next week.

**Comment by orangejulius** [comment]
Sometime last week we updated our dependency on the `elasticsearch` module, to one that supports node 4+. @devTristan, can you give this another try on the master branch? Everything should work now.

**Comment by orangejulius** [comment]
I've been using Node4 with pelias for a few weeks now, and we have been running TravisCI tests against node 4 and 5 for all our repos for a month or so now. I'm now confident enough things are working in node 4 and 5 that I'm closing this issue, but if anything does crop up again please let us know!
